services:
  app:
    image: "${IMAGE_NAME?Variable not set}:${TAG-latest}"
    container_name: intempus-synchronizer-app
    build:
      context: .
      target: dev
    restart: always
    ports:
      - 8000:8000
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      CORS_ORIGINS: ${CORS_ORIGINS}
      INTEMPUS_API_BASE_URL: ${INTEMPUS_API_BASE_URL}
      INTEMPUS_API_KEY: ${INTEMPUS_API_KEY}
      SYSTEM_B_API_BASE_URL: ${SYSTEM_B_API_BASE_URL}
      INCREMENTAL_SYNC_INTERVAL_SECONDS: ${INCREMENTAL_SYNC_INTERVAL_SECONDS}
      FULL_SYNC_INTERVAL_SECONDS: ${FULL_SYNC_INTERVAL_SECONDS}
    volumes:
      - ./.venv/lib:/intempus_synchronizer/.venv/lib
      - ./app:/intempus_synchronizer/app
      - ./data:/intempus_synchronizer/data
